const MessengerAction = {
  GET_CONVERSATION_LIST:"GET_CONVERSATION_LIST",
  SET_CONVERSATION_LIST: 'SET_CONVERSATION_LIST',
  SEND_MESSAGE:"SEND_MESSAGE",
  SET_CART_LIST:"SET_CART_LIST",
  SET_PRODUCTS_LIST:"SET_PRODUCTS_LIST",
  GET_PRODUCTS_LIST:"GET_PRODUCTS_LIST",
  SET_CATEGORY:"SET_CATEGORY",
  // GET_PEOPLE_PROFILE:"GET_PEOPLE_PROFILE",
  // SET_PEOPLE_PROFILE: 'SET_PEOPLE_PROFILE',
  // SET_FOLLOW_PEOPLE: 'SET_FOLLOW_PEOPLE',
};

export default MessengerAction;
